export const PROFILE_PROMPTS = [
  "Dating me is like...",
  "My simple pleasures...",
  "I'm convinced that...",
  "My most controversial opinion is...",
  "I'll fall for you if...",
  "The best way to ask me out is...",
  "My love language is...",
  "I'm looking for someone who...",
  "Together we could...",
  "I want to know more about...",
  "A non-negotiable for me is...",
  "My ideal Sunday is...",
  "I geek out on...",
  "My hidden talent is...",
  "I’m overly competitive about...",
  "The hallmark of a good relationship is...",
  "My golden rule...",
  "I recently discovered that...",
  "My favorite way to waste time is...",
];
